### ISSUE TITLE
"Unexpected token )" from recent commit

### ISSUE THREAD

**Issue by OniLink** [express-handlebars/express-handlebars#31]
Apologies, I didn't get a chance to type anything before Github submitted the issue? I'm having a bad day.

A recent commit (https://github.com/express-handlebars/express-handlebars/commit/90399e182ef60242ea8fdd249bd99efac8d95c53) made a change to lib/express-handlebars.js

Line 229 had a trailing comma added to the end which causes any simple app using express-handlebars to fail with an unexpected token error on line 230.

Removing the trailing comma appears to fix the issue.

**Comment by UziTech** [comment]
trailing commas were added in node 6. What version of node are you running?

**Comment by UziTech** [comment]
Actually it looks like it was node v8 that added trailing commas in function parameters. Since that version is no longer supported by node as of January 1st 2020 and that commit was committed on April 2nd 2020 I don't see any reason to continue supporting it in new versions.

If you want to continue using express-handlebars in node v8 I would recommend pinning to version 4.0.1 or creating a fork and using the fork in your application.
