### ISSUE TITLE
What about css styling?

### ISSUE THREAD

**Issue by ClaudioRowe** [express-handlebars/express-handlebars#393]
How do i add styling? It is not using when i reference it on the main on replit, and i can't find info on that on your documentation

**Comment by UziTech** [comment]
You can add CSS styling like any other html.

With style tags

```html
<style>
body {
  background: red;
}
</style>
```

or  link tag

```html
<link href="/path/to/styles.css" rel="stylesheet">
```

**Comment by ClaudioRowe** [comment]
when i add it on the main layout, does it reference the style file from there or from where the partial is calling it?

**Comment by UziTech** [comment]
It references it on the client side from the URL that is given. Express-handlebars does not add the css on the server side. You need to serve the css file some other way.

**Comment by ClaudioRowe** [comment]
![image](https://user-images.githubusercontent.com/60100296/182906042-fb414f77-1d28-458b-b09d-d40173a50132.png)

I'm calling it that way but it won't work, it is right? As it is the main layout that has the reference

**Comment by UziTech** [comment]
The URL `href="../../style/style.css"` should be a public URL. In other words if you enter that URL in the browser you should see your css file. Express-handlebars DOES NOT import the css for you on the server side.

> How do I serve css to be public on the client side?

That is a question for stackoverflow.com since the answer will not have anything to do with express-handlebars.
